name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - alpha

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # used for semantic release
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Initialize packages
        run: pnpm run init
      - name: Lint Files
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
      - name: Build
        run: pnpm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release
